version: "3.7"
services:
  app:
    image: learning24
    restart: unless-stopped
    volumes:
      - ./:/var/www
     #- ./storage/app/public:/var/www/storage/app/public
      - ./php:/usr/local/etc/php/conf.d
        #- ./bootstrap/cache:/var/www/bootstrap/cache
        #- ./storage:/var/www/storage
      - ./imagick:/etc/ImageMagick-6
    working_dir: /var/www
    env_file: .env
      
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
