version: "3"
services:
  ebook:
    image: iamapinan/php-nginx-mongo:alpine
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/app
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - backend
      
  mysql:
    image: mysql:5.6
    container_name: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=ebook_db
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=ebook_db
      - MYSQL_PASSWORD=password
    networks:
      - backend
    ports:
      - "3306"

  redis_cache:
    image: redis
    container_name: redis_cache
    restart: always
    ports:
      - "6379"
    networks:
      - backend

networks:
  backend:
    driver: bridge
