version: "3.7"
services:
  app:
    build: .
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
     #- ./storage/app/public:/var/www/storage/app/public
      - ./php:/usr/local/etc/php/conf.d
        #- ./bootstrap/cache:/var/www/bootstrap/cache
        #- ./storage:/var/www/storage
    networks:
      - public_net
    env_file:
      - .env

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - public_net

networks:
  public_net:
    external: true
